### ISSUE TITLE
Container fails to build on Apple M1 (steamcmd.sh: line 76: 12 Segmentation fault)

### ISSUE THREAD

**Issue by rmccarthy24** [LacledesLAN/gamesvr-svencoop#60]
Not sure why this is an issue now but it seems to be. 
I'm running on an M1 mac pro and I haven't made any changes to the docker build file that I feel would cause this error. If you have any insight let me know. I am willing to provide details when asked. 
Thanks

![Screenshot 2024-11-02 at 17 30 46](https://github.com/user-attachments/assets/bff3a46c-7515-46b2-b416-4a9f7071f68f)

**Comment by rmccarthy24** [comment]
Dug a little deeper and I get a /app/steamcmd.sh: not found error.

**Comment by dudleycodes** [comment]
Apple's `M<#>` chips are ARM, whereas this Docker image is meant for `x86_64`.

@rmccarthy24 - can you show the `docker build` command you are using?  Make sure to try adding `--platform linux/amd64` as one of the build params, so that docker on your M1 emulates X86_64 instructions.

**Comment by corrosive4354** [comment]
You can add the --platform linux/amd64 option when building a Docker image. This will make Docker emulate x86_64 instructions on the M1, which may solve the compatibility problem. The sample command is as follows:
docker build --platform linux/amd64 -t your-image-name .

Also, seeing that you are using Docker, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use than Docker on Mac

**Comment by dudleycodes** [comment]
Did this help you @rmccarthy24 ?

**Comment by dudleycodes** [comment]
Haven't had any updates. Assuming fixed. Closing issue.
